#!/bin/sh
set -e

# Ajustar los permisos del archivo de contraseña
chmod 600 /etc/x11vnc.passwd
chown root:root /etc/x11vnc.passwd

# Recargar systemd, habilitar y arrancar el servicio x11vnc
systemctl daemon-reload
systemctl enable sddmx11.service
systemctl start sddmx11.service
